spring:
  application:
    name: shopping cart
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_cart?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates
